elementary/switchboard-plug-display

src/DisplaysView.vala

Center monitors when they're moved

---

src/DisplayPlug.vala
src/DisplayWidget.vala
src/DisplayWindow.vala
src/DisplaysView.vala
src/MirrorDisplay.vala

Updates license headers to the current FSF address. 
Fixes #46

Update FSF address

---

src/DisplayPlug.vala
src/Views/DisplaysView.vala

Nice and self contained so we can have pages

Move displays view code to its own class in Views

---

src/Views/NightLightView.vala

Default mark

---

src/CMakeLists.txt
src/Interfaces/NightLightManager.vala
src/Views/NightLightView.vala

Fixes: https://github.com/elementary/wingpanel-indicator-nightlight/issues/27

Clear NightLight snooze on property change

---

src/Interfaces/MutterDisplayConfig.vala

Fix screen rotation labels

---

src/Widgets/DisplayWidget.vala

Fix wrong rotation preview

---

src/DisplayPlug.vala

Alterations to get better results when searching for sub settings. See: https://github.com/elementary/applications-menu/pull/133

Plug search improvements

---

src/Widgets/DisplayWidget.vala

Change "Rotation" label to "Screen Rotation"

---

src/Widgets/DisplayWidget.vala

DisplayWidget: Use Gtk.MenuButton instead of ToggleButton

---

data/io.elementary.switchboard.display.appdata.xml.in
data/meson.build
po/extra/POTFILES

Change RDNN to io.elementary.switchboard.display

---

src/Views/NightLightView.vala

Fix nightlight can't parse minutes in schedules

---

src/Widgets/DisplaysOverlay.vala

DisplaysOverlay: Update copyright header

---

src/Widgets/DisplaysOverlay.vala

This should fix the last remaining linting errors in this plug.

DisplaysOverlay: fix linting errors

---

src/Views/DisplaysView.vala

Since actionbar now has padding by default in greenfield

DisplaysView: Fix actionbar padding and alignment

---

src/Interfaces/NightLightManager.vala
src/Objects/MonitorMode.vala
src/Utils.vala
src/Widgets/DisplayWidget.vala
src/Widgets/DisplaysOverlay.vala

Compile with no warnings on Hera

Fix compile warnings

---

src/Objects/MonitorManager.vala
src/Objects/VirtualMonitor.vala
src/Widgets/DisplayWidget.vala

Fixes #131 
There have been a few attempts at solving this issue, most of which seem to revolve around redesigning large parts of the plug and then they never get much traction as a result.
This fixes the linked issue in the most minimally invasive way possible.

Fix use this display switch

---

src/Widgets/DisplayWindow.vala
src/meson.build

Changing the label widgets to use Hdy.ApplicationWindow (For rounded corners).
Moving the tag away from the borders, for better visibility.
Fixes #12 .

Adding rounded corner for display tags

---

src/Widgets/DisplayWindow.vala

DisplayWindow: stick to all workspaces

---

data/display.appdata.xml.in
src/Views/NightLightView.vala

Redesign to use modern patterns and layout. Clean up code and update to latest style while here
Fixes #346

NightLightView: Redesign and cleanup

---

data/Filters.css
data/io.elementary.switchboard.display.gresource.xml
po/POTFILES
src/DisplayPlug.vala
src/Views/DisplaysView.vala
src/Views/FiltersView.vala
src/Views/NightLightView.vala
src/meson.build

Create Filters View

---

debian/control

Recommend Gala 7.1.0 for color assistance filters
Recommend GSD for night light

Control: recommend Gala and GSD

---

src/Widgets/DisplaysOverlay.vala

Review with hide whitespace
In GTK 4 we don't have a `get_children` function, so instead keep a list of display widgets. This also saves us having to check types

DisplaysOverlay: keep a list of widgets

---

src/Views/DisplaysView.vala

* Bump copyright header
* Use box instead of grid
* explicit margins
* code style

DisplaysView: Gtk4 prep

---

meson.build

Release 8.0.2
