src/CMakeLists.txt, src/DisplayPlug.vala, src/Views/DisplaysView.vala, src/Views/NightLightView.vala
=>  Add NightLight view

src/DisplayPlug.vala
For some reason, both the indicator and the plug stopped showing up on me due to the SettingsSchemaSource not finding the schema.
I've had this happen before, and setting the param to `true` fixes it 
https://valadoc.org/gio-2.0/GLib.SettingsSchemaSource.lookup.html
=> Recursive lookup of the settings

src/DisplayPlug.vala
Fixes #73.
Seems like someone had copied over the call to `show_windows` but forgot to actually change it to hide the badge.
=> Fix display badge displaying when in night light view

po/en_GB.po, src/Objects/Monitor.vala, src/Objects/MonitorManager.vala, src/Objects/VirtualMonitor.vala, src/Widgets/DisplayWidget.vala
* Update resolution when we receive a signal that the current state changed (e.g clicking the "Restore previous setting" in the "Revert resolution dialog")
* Make rotation UI work
* Update rotation UI when it changes
* Simplify updating display view when rotation changes
* Move some core functions to `VirtualMonitor`
* Add an `id` property to `VirtualMonitor` to enable `MonitorManager` to update existing virtual monitors when state changes
=> Update UI when configuration changed

src/Widgets/DisplayWidget.vala
A one-line fix so that rotated/flipped monitor previews don't always revert to the "None" transform in the dropdown when the plug is initialized.
=> Fix #108 by selecting correct transform at startup

src/Interfaces/MutterDisplayConfig.vala, src/Objects/Monitor.vala, src/Objects/MonitorManager.vala, src/Objects/VirtualMonitor.vala
Sending another PR because the first was bundled with my another PR, explaining, some displays are being equal so I made a hash that joins connector, serial, display name and vendor.
=> Fixes crash with multidisplay

src/Widgets/DisplayWidget.vala, src/Widgets/DisplaysOverlay.vala
* Also style the primary icon and more settings icon
* Make the activated primary icon a contrasting color for greater visibility
* Only set borders on the widget, not the window in the corner of the display
* Reserve slate for the disabled color
=> More CSS and color adjustments

src/Widgets/DisplayWidget.vala, src/Widgets/DisplaysOverlay.vala
See: #156 
Used 100 variants of official palette to make it easier on the eye. Added a border with the 500 variant.
https://elementary.io/docs/human-interface-guidelines#color
Examples:
=> Tweak display colors

src/Utils.vala, src/Views/DisplaysView.vala
Fixes #116 
Instead of assuming that a touchscreen implies an accelerometer, use SensorProxy to ask if there is an accelerometer.
This is the bus that Mutter watches for rotation changes, so if we use this, we're guaranteed to show the switch if auto-rotation is supported.
I don't have a snazzy auto rotating laptop though, so can someone that does check that the switch still appears for them? :smile:
=> Use SensorProxy to detect accelerometer

src/Views/DisplaysView.vala
Related to https://github.com/elementary/switchboard-plug-display/issues/130
=> Add 3× scaling setting

meson.build, src/Config.vala.in, src/DisplayPlug.vala, src/meson.build
Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)
=> l10n: Correctly setup the locales

src/Objects/MonitorManager.vala, src/Objects/VirtualMonitor.vala
Fixes #314 
Follow up to #311 
It wasn't possible to disable monitors on the left or above the other enabled monitors as doing so would leave a gap in the "virtual monitors" co-ordinate space where mutter expects them to start from 0,0.
So, once we've filtered out the disabled monitors, offset them by their minimum co-ordinate to get them arranged around 0,0.
I've additionally made `get_current_mode_size` return the preferred size for disabled monitors instead of a hardcoded value, which makes positioning and re-enabling disabled monitors easier.
=> Remove offsets from virtual monitors

src/Widgets/DisplayWidget.vala
Fixes #312. Since a single display will always be the primary display, we don't need to bind to that property. I moved the `set_primary` down to ensure the switch is constructed first, then set the sensitivity when setting the primary display to ensure it stays in sync. Also fixed capitalization while I was here.
=> DisplayWidget: Disable use_switch on primary display

src/Widgets/DisplayWidget.vala
Fixes #338 
This patch checks whether the `is_preferred` flag has been set on any of the modes and if so then only add those modes to the recommended resolution list and the rest to the other list.
If none of the modes have the `is_preferred` flag set to true then the current behaviour is maintained.
Current behaviour (before this patch) is that the max supported resolutions aspect ratio (not necessarily native) are placed into the recommended list with undesirable (?) results, at least on my 4K UHD (3840x2160) TV with native aspect ratio of 16:9
See the before and after screenshots:
BEFORE:
AFTER:
=> Prefer the resolution modes marked is_preferred

src/DisplayPlug.vala
Adds handlers for the following "deeplinks" (not sure what the conventional term is!):
- `settings://display` - To the `Displays` tab
- `settings://display/filters` - To the `Filters` tab.
This should allow the app menu to correctly open this plug at the correct tab from search results, as referenced in #360
=> Add missing deeplink handlers

src/Widgets/DisplayWidget.vala
* Use event controllers
* explicit margins
* code style
* Use Granite.SwitchModelButton in a popover instead of label and switch
* Use Granite.HeaderLabel and set mnemonic widgets for a11y
=> DisplayWidget: Gtk4 prep

src/Widgets/DisplaysOverlay.vala
Can't subclass overlay in Gtk4
=> DisplaysOverlay: put overlay in a box

data/Display.css, src/Widgets/DisplayWidget.vala, src/Widgets/DisplaysOverlay.vala
In latest GTK 4, the only non-deprecated use of StyleContext is to set a provider for the whole screen. Since we have a finite number of monitor colors, we really don't need to generate this CSS. Instead we can just have a set number of color style classes and then assign a style class to each display widget.
* Set the CSS name of display widgets
* Create color-number classes with predefined styles
* Tiny style stuff, make the label slightly bolder, give the widget a little rounded corner, clear icon palette to improve contrast of star icons
* Add one style provider to the screen, not to each widget for each color
=> Styles: Gtk4 prep

src/Widgets/DisplaysOverlay.vala
Closes #384
Does what was suggested by @zeebok there and also checks actually active monitors. I'm not to deep in the codebase but this is what makes sense to me. Also removes some debug warnings. 
Note that this still doesn't check if config actually changed only if it's valid. 
Should probably be tested with multiple monitors as well
=> Fix apply unsensitive with only a single monitor

src/Objects/MonitorManager.vala, src/Objects/VirtualMonitor.vala, src/Widgets/DisplayWidget.vala
=> Use mutter provided supported scales

data/Display.css
The labels inside the popover for display configuration had also the text shadow applied which made them look very blurry. Make sure we only apply the text shadow to the centered label of the display widget.
=> DisplayWidget: Fix text-shadow for children 

src/Objects/MonitorManager.vala, src/Objects/VirtualMonitor.vala, src/Widgets/DisplaysOverlay.vala
Fixes #374 
Closes #406 
- Sets monitores before scale setting
- Fix overlay not being updated after enable mirrored display
- Fix display widgets removing at overlay update
=> Fix crash on enabling mirror display

src/Objects/MonitorManager.vala, src/Views/DisplaysView.vala
Fixes #419 by creating adding a new monitor when we already finished setup it and fixes the display arrangement when adding or removing a monitor.
=> Fix crash and display arrangement when pluging new monitor
